name: Python CI

# trigger thw workflow on any pusht ot he main branch or pull request 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # check out the code from the repository
            - uses: actions/checkout@v2

            # setup a python environemnt
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            
            # install dependencies
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            # run the tests
            - name: Run tests
              run: pytest

